### ISSUE TITLE
InvalidOperationException: Property 'JsonResult.SerializerSettings'

### ISSUE THREAD

**Issue by agoerner** [maikebing/SilkierQuartz#61]
Hello, 

Always when I save Trigger or Jobs I get an internal error. Saving works, but the return Json()... runs into this exception: Any Idea? 

System.InvalidOperationException: Property 'JsonResult.SerializerSettings' must be an instance of type 'System.Text.Json.JsonSerializerOptions'.
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.GetSerializerOptions(JsonResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor.ExecuteAsync(ActionContext context, JsonResult result)
![grafik](https://user-images.githubusercontent.com/35223383/107187214-f4c65d00-69e5-11eb-895d-13ffde9f1845.png)

DB-Setup: SQL Server
Version .net 5.0 

Thanks!

**Comment by agoerner** [comment]
AddNewtonsoft() resolved my issue
